version = 1

[[annotations]]
path = [
  ".editorconfig",
  ".gitignore",
  "CNAME",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2020-2026 LibreCode coop and contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"
